version: "3"

services:
  app: 
    container_name: nestjs_api
    build: .
    # Command to dev -> yarn start:dev
    # Command to debug -> yarn start:debug
    command: yarn start:debug
    environment: 
      NODE_ENV: development
      PORT: 3000 
    ports:
      - "3000:3000"
      # Port to debug
      - "9229:9229"
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules

  database:
    container_name: nestjs_postgresdb
    image: postgres
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

  redis:
    container_name: nestjs_redis
    image: redis
    command: redis-server --requirepass docker --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /usr/app/Redis:/var/lib/postgresql/data
    